### PR TITLE
add hero-section code

### PR DESCRIPTION
**Pull request by Aaron-Mandela-Okullo**

### CODE REVIEW

**Comment by fatuma65** [comment]
The code looks good Aaron, could you transfer it to the main index.html file.

**Comment by fatuma65** [comment]
@Aaron-Mandela-Okullo Could you remove the code on lines 19 and 20 and its CSS, since it's unnecessary and maybe add a main tag showing that this is a main section? Also, put the CSS code for the hero section in the index.css file and remove the hero-section.css file and its link in the index.html file on line 15.

**Comment by Aaron-Mandela-Okullo** [comment]
I didn't work on lines 19 and 20 but I worked on it like you asked. Thanks

**Comment by fatuma65** [comment]
Nice work, code looks good to me

**Pull request merged**
